spring.application.name=restaurante
server.port=8080

#               DATABASE
# db = PostgreSQL Docker Container's name.
spring.datasource.url=jdbc:postgresql://db:5432/restaurante
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate - SQL debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true
#Logging
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

#               SWAGGER
# Swagger - UI path (Ex.:http://localhost:<server.port>/my-docs)
springdoc.swagger-ui.path=/my-docs
# Para desabilitar a URL em produção (UI)
#springdoc.swagger-ui.enabled=false
# Swagger - Documentação JSON path (Ex.:http://localhost:<server.port>/api-docs)
springdoc.api-docs.path=/api-docs
# Para desabilitar a URL em produção (API-DOCS)
#springdoc.api-docs.enabled=false

#           PROBLEM DETAIL
spring.mvc.problem-details.enabled=true

#               LOGGING
logging.level.org.springframework.web=DEBUG