CREATE TABLE address
(
    id           BIGINT GENERATED ALWAYS AS IDENTITY,
    street       VARCHAR(150) NOT NULL,
    number       VARCHAR(10)  NOT NULL,
    complement   VARCHAR(100),
    neighborhood VARCHAR(100) NOT NULL,
    city         VARCHAR(100) NOT NULL,
    state        CHAR(2)      NOT NULL,
    zip_code     VARCHAR(8)   NOT NULL,

    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE person
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    name       VARCHAR(150) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    cpf        CHAR(11) NOT NULL, -- Somente dígitos
    address_id BIGINT,

    CONSTRAINT pk_person PRIMARY KEY (id),
    CONSTRAINT fk_person_address FOREIGN KEY (address_id) REFERENCES address (id),
    CONSTRAINT uk_customer_cpf UNIQUE (cpf),
    CONSTRAINT ck_customer_cpf CHECK (cpf ~ '^[0-9]{11}$')
);

-- Index em person.email
CREATE UNIQUE INDEX uk_person_email ON person (LOWER(email));


CREATE TABLE user_type
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE,

    CONSTRAINT pk_user_type PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uk_user_type_name ON user_type (LOWER(name));


CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    person_id     BIGINT       NOT NULL,
    login         VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_person_id UNIQUE (person_id),
    CONSTRAINT fk_app_user_person FOREIGN KEY (person_id)
        REFERENCES person (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_app_user_login ON app_user (LOWER(login));

CREATE TABLE app_user_type
(
    app_user_id  BIGINT NOT NULL,
    user_type_id BIGINT NOT NULL,

    CONSTRAINT pk_app_user_type PRIMARY KEY (app_user_id, user_type_id),
    CONSTRAINT fk_app_user_type_app_user FOREIGN KEY (app_user_id)
        REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_app_user_type_user_type FOREIGN KEY (user_type_id)
        REFERENCES user_type (id) ON DELETE RESTRICT
);

CREATE INDEX idx_app_user_type_user_type ON app_user_type (user_type_id);


CREATE TABLE customer
(
    person_id BIGINT   NOT NULL,
    created_on TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_customer PRIMARY KEY (person_id),
    CONSTRAINT fk_customer_person FOREIGN KEY (person_id)
        REFERENCES person (id) ON DELETE CASCADE
);


CREATE TABLE restaurant_owner
(
    person_id BIGINT NOT NULL,
    created_on TIMESTAMPTZ NOT NULL DEFAULT now(),
    business_email VARCHAR(255) NOT NULL,

    CONSTRAINT pk_restaurant_owner PRIMARY KEY (person_id),
    CONSTRAINT fk_restaurant_owner_person FOREIGN KEY (person_id)
        REFERENCES person (id) ON DELETE CASCADE
);

CREATE TABLE restaurant
(
    id           BIGINT GENERATED ALWAYS AS IDENTITY,
    name         VARCHAR(150) NOT NULL,
    cnpj         CHAR(14)     NOT NULL,
    cuisine_type VARCHAR(50)  NOT NULL,
    owner_id     BIGINT       NOT NULL,
    address_id   BIGINT       NOT NULL,

    CONSTRAINT pk_restaurant PRIMARY KEY (id),
    CONSTRAINT uk_restaurant_cnpj UNIQUE (cnpj),
    CONSTRAINT uk_restaurant_address_id UNIQUE (address_id),
    CONSTRAINT ck_restaurant_cnpj CHECK (cnpj ~ '^[0-9]{14}$'
) ,
    CONSTRAINT fk_restaurant_owner      FOREIGN KEY (owner_id)
        REFERENCES restaurant_owner (person_id) ON DELETE RESTRICT,
    CONSTRAINT fk_restaurant_address    FOREIGN KEY (address_id)
        REFERENCES address (id)
);

CREATE INDEX idx_restaurant_owner ON restaurant (owner_id);


CREATE TABLE opening_hours
(
    id            BIGINT GENERATED ALWAYS AS IDENTITY,
    restaurant_id BIGINT   NOT NULL,
    day_of_week   SMALLINT NOT NULL, -- 1 a 7 (1 = segunda, 7 = domingo)
    opening_time  TIME     NOT NULL,
    closing_time  TIME     NOT NULL,

    CONSTRAINT pk_opening_hours PRIMARY KEY (id),
    CONSTRAINT uk_opening_hours_shift UNIQUE (restaurant_id, day_of_week, opening_time),
    CONSTRAINT ck_opening_hours_day_of_week CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT ck_opening_hours_times CHECK (opening_time <> closing_time),
    CONSTRAINT fk_opening_hours_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- menu_item
-- -----------------------------------------------------------------------------
CREATE TABLE menu_item
(
    id            BIGINT GENERATED ALWAYS AS IDENTITY,
    restaurant_id BIGINT         NOT NULL,
    name          VARCHAR(150)   NOT NULL,
    description   TEXT           NOT NULL,
    price         NUMERIC(10, 2) NOT NULL,
    dine_in_only  BOOLEAN        NOT NULL DEFAULT FALSE, -- Disponibilidade para pedir apenas no Restaurante.
    photo_url     VARCHAR(500),                          -- Foto do prato (como estávamos fazendo um serviço de back-end e a foto não será utilizada, podemos apenas salvar um caminho de onde a foto estaria)

    CONSTRAINT pk_menu_item PRIMARY KEY (id),
    CONSTRAINT ck_menu_item_price CHECK (price >= 0),
    CONSTRAINT fk_menu_item_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (id) ON DELETE CASCADE
);
